app: mkxp
  union: true

ingredients:
  dist: bionic
  sources:
    - deb file:/packager/output/ ./
    - deb http://archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse
    - deb http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
    - deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse
    - deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
  exclude:
    - libgl1-mesa-dev
    - libegl-mesa0

scripts:
  - mkdir -p lib/x86_64-linux-gnu
  - cp /lib/x86_64-linux-gnu/libnsl[-.]* lib/x86_64-linux-gnu/
  - cp usr/share/applications/mkxp.desktop ./
  - cp usr/share/icons/hicolor/128x128/apps/mkxp.png ./
